### ISSUE TITLE
Fix search page to ignore case.

### ISSUE THREAD

**Issue by sethlaw** [nVisium/grails.nV#37]
Search functionality should ignore case. XSS must work using the search box for reflected XSS demos.

**Comment by cmalekpour** [comment]
With 0d4ec2784351b19c4babab20b3b5851b0b2e228e, all listing search queries are base64'd. This helps bypass anti-XSS features in browsers and it also conveniently disguises XSS attacks in URLs.

To test, try searching for ````<script>alert(1);</script>````
