### ISSUE TITLE
Company Management

### ISSUE THREAD

**Issue by sethlaw** [nVisium/grails.nV#38]
Allow the administrator to create and update the companies listed, as well as any associated accounts.

**Comment by cmalekpour** [comment]
With 93735f9cb551d9f9244e779e3087c2f9d23e85a1, admins can now create companies right from the company page. Both admins and company employees can edit the company listing from that page as well. 

Admins can also generally edit accounts from the admin panel (linked in the top right of the oage).

**Comment by cmalekpour** [comment]
As of 18b9c13c17f52a555479e2619dac09d9a10e0824, each company lists its employees on the company page. Administrators can click on each name to access the profile, and then edit the profile from the included "Edit Profile" button. This button will only show up to users with sufficient privileges to edit other accounts
